[build]
  base = "frontend"
  publish = "public"
  command = "echo 'Static site - no build needed'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://tu-app.railway.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  BACKEND_URL = "https://tu-app.railway.app"