[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
    'cd backend',
    'npm ci --only=production',
    'npx prisma generate'
]

[phases.build]
cmds = ['echo "No build needed"']

[start]
cmd = 'cd backend && npm start'