[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = [
    'cd backend',
    'npm ci --only=production --silent --prefer-offline',
    'npx prisma generate --no-engine'
]

[phases.build]
cmds = [
    'echo "Build optimization completed"',
    'npm run postbuild --if-present'
]

[variables]
NODE_ENV = 'production'
NPM_CONFIG_CACHE = '/tmp/.npm'

[start]
cmd = 'cd backend && node --max-old-space-size=256 --optimize-for-size server.js'