[variables]
NODE_ENV = 'production'

[phases.install] 
cmds = ['cd backend && npm ci --omit=dev']

[phases.build]
dependsOn = ['install']
cmds = ['cd backend && npx prisma generate']

[start]
cmd = 'cd backend && npx prisma db push --accept-data-loss && node server.js'