[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = [
    'cd backend && npm install --production'
]

[phases.build]
cmds = [
    'cd backend && npx prisma generate',
    'cd backend && npx prisma db push --accept-data-loss'
]

[start]
cmd = 'cd backend && node server.js'

[variables]
NODE_ENV = 'production'